name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: conventionalcommits
        name: Conventional Commits
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: "true"
          skip-on-empty: "false"
          output-file: "false"
          create-summary: true
          preset: conventionalcommits

      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.conventionalcommits.outputs.tag }}
          release_name: ${{ steps.conventionalcommits.outputs.tag }}
          body: ${{ steps.conventionalcommits.outputs.clean_changelog }}
